name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build for GitHub
        run: ./gradlew build
      - name: Publish to GitHub
        uses: xresloader/upload-to-github-release@v1
        with:
          file: "./build/libs/*!(dev).jar"
          update_latest_release: true
